services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      TZ: 'Asia/Ho_Chi_Minh'
      PGTZ: 'Asia/Ho_Chi_Minh'
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./docker-data/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
  
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"